project:
  type: website

website:
  title: "Data analytics and research blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

