project:
  type: website

website:
  title: "Portfolio"
  page-footer: "Blog made with [Quarto](https://quarto.org/) 🧡 by Jennifer HY Lin ©2022"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    

editor: visual

comments:
  giscus:
    repo: jhylin/Data-analytics-and-research-blog