project:
  type: website

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
    
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

