project:
  type: website
  # Weird problem of Quarto not detecting new post and save a copy to _site folder
  # Manually uploaded new post folder to GitHub which worked 19/11/22
  # Below was codes trialled, but did not work
  #resources: 
     #- "*.jpg"
     #- "*.qmd"

website:
  title: "Home"
  page-footer: "Blog made with ❤️ in [Quarto](https://quarto.org/) by Jennifer HY Lin © 2022 📕 Citation as author and blog URL link if used"
  google-analytics: "G-5CHVP3K63C"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
      - text: Resume
        href: https://jhylin.github.io/CV_resume/
  repo-url: https://github.com/jhylin/Data_in_life_blog
  repo-actions: [issue]
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    

editor: visual

comments:
  giscus:
    repo: jhylin/Data_in_life_blog