project:
  type: website

website:
  title: "Home" 
  page-footer: "Website made with ❤️ in [Quarto](https://quarto.org/) by Jennifer HY Lin © 2022 - 2023 📕 Citation as author and URL link if used"
  google-analytics: "G-5CHVP3K63C"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - icon: mastodon
        href: https://fosstodon.org/@jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
      - text: Portfolio
        href: https://www.datascienceportfol.io/jhylin
      - text: CV
        href: https://jhylin.github.io/CV_resume_quarto/
  repo-url: https://github.com/jhylin/Data_in_life_blog
  repo-actions: [issue]
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    

editor: visual

comments:
  giscus:
    repo: jhylin/Data_in_life_blog